### ISSUE TITLE
Issues beaconwars 1

### ISSUE THREAD

**Issue by CyberoptiqIsCool** [TKDKid1000/CyberhubMC#1]
1. armor is kept on death
2. shop is unfair, and many items are either too expensive or too cheap
3. beacons take too long to break, causing players to respawn before the beacon is broken
4. obsidian is op, considering how cheap it is and how difficult it is to rebuy pickaxes
5. too many emeralds and nether stars can spawn at a time, creating the possibility to find 30+ emeralds in the generator
6. health from the hub is kept after the game starts
7. food must be bought in bulk. This isn't a Costco, is it?
8. beacons drop when destroyed, nothing serious, just annoying because other people can place a beacon down on their island and depend they have one still alive

**Comment by TKDKid1000** [comment]
> 1. armor is kept on death
> 2. shop is unfair, and many items are either too expensive or too cheap
> 3. beacons take too long to break, causing players to respawn before the beacon is broken
> 4. obsidian is op, considering how cheap it is and how difficult it is to rebuy pickaxes
> 5. too many emeralds and nether stars can spawn at a time, creating the possibility to find 30+ emeralds in the generator
> 6. health from the hub is kept after the game starts
> 7. food must be bought in bulk. This isn't a Costco, is it?
> 8. beacons drop when destroyed, nothing serious, just annoying because other people can place a beacon down on their island and depend they have one still alive

Yes, It is costco.

**Comment by TKDKid1000** [comment]
> 1. armor is kept on death
> 2. shop is unfair, and many items are either too expensive or too cheap
> 3. beacons take too long to break, causing players to respawn before the beacon is broken
> 4. obsidian is op, considering how cheap it is and how difficult it is to rebuy pickaxes
> 5. too many emeralds and nether stars can spawn at a time, creating the possibility to find 30+ emeralds in the generator
> 6. health from the hub is kept after the game starts
> 7. food must be bought in bulk. This isn't a Costco, is it?
> 8. beacons drop when destroyed, nothing serious, just annoying because other people can place a beacon down on their island and depend they have one still alive

Armor should no longer be kept on death. Shop can be modified by anytime and will do that as soon as I get the wanted prices. Beacons instabreak now. Slowing down spawn rate of stars and emeralds. Health from hub is no longer kept. Food is updated to 4 for 4. Beacons no longer drop.
